// Config for the regression specs auto-generated by qa-run (opted into per
// run) under tests/regression/. Each spec loads its own env vars via
// scripts/load-env.mjs, so this config just needs to find and run them.
import { defineConfig } from "@playwright/test";

export default defineConfig({
  testDir: "./tests/regression",
  timeout: 30_000,
  retries: 0,
  reporter: "list",
  use: {
    headless: true,
    screenshot: "only-on-failure",
  },
});
